---
# tasks file for prometheus-install

- name: Create Prometheus group
  become: yes
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: present
- name: Create Prometheus user
  become: yes
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: present
- name: Get prometheus distr
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "~/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
- name: Unarchive prometheus
  ansible.builtin.unarchive:
    src: "~/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    remote_src: yes
    dest: "/tmp/"
- name: Create dir for prometheus config
  become: yes
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
- name: Create dir for prometheus data
  become: yes
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
- name: Copy Prometheus archive content to dirs and clean
  become: yes
  ansible.builtin.shell: |
    cp /tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus /usr/local/bin
    cp /tmp/prometheus-{{ prometheus_version }}.linux-amd64/promtool /usr/local/bin
    cp /tmp/prometheus-{{ prometheus_version }}.linux-amd64/tsdb /usr/local/bin
    cp -r /tmp/prometheus-{{ prometheus_version }}.linux-amd64/console\* /etc/prometheus
    rm -rf /tmp/prometheus-{{ prometheus_version }}.linux-amd64

- name: Change prometheus dirs owner
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: directory
    recurse: yes
  loop:
    - /var/lib/prometheus
    - /etc/prometheus

- name: Change prometheus bins owner
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  loop:
    - /usr/local/bin/prometheus
    - /usr/local/bin/promtool

- name: Copy Prometheus config template
  become: yes
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
- name: Copy rules for alertmanager
  become: yes
  ansible.builtin.copy:
    src: files/rules.yml
    dest: /etc/prometheus/rules.yml
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644    
- name: Copy prometheus service template
  become: yes
  ansible.builtin.template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"
    owner: root
    group: root
- name: Start prometheus service
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: started 
    enabled: yes
    daemon_reload: true

    