---
# tasks file for nginx-proxy-install
- name: Config nginx
  become: yes
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Create ACME Challenge directory
  become: yes
  ansible.builtin.file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    mode: 0755
- name: Install Certbot
  become: yes
  ansible.builtin.apt:
    name: certbot
    state: present
    update_cache: yes 
- name: Copy cli.ini
  become: yes
  ansible.builtin.copy:
    src: files/cli.ini
    dest: /etc/letsencrypt/cli.ini
    mode: 0644
- name: get test cerificates
  become: yes
  ansible.builtin.command: "certbot certonly --test-cert --agree-tos --no-eff-email -q --email {{ email }} -d {{ domain_name }} -d www.{{ domain_name }} -d gitlab.{{ domain_name }} -d grafana.{{ domain_name }} -d prometheus.{{ domain_name }} -d alertmanager.{{ domain_name }}"

- name: Copy proxy config templates
  become: yes
  ansible.builtin.template:
    src: "templates/{{ item }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    mode: 0644
  with_items: "{{ nginx_proxy_configs }}"
  notify: Reload Nginx service