---
# tasks file for mysql-install
- name: Install MySQL 5.7 repo
  become: yes
  ansible.builtin.yum:
    name: http://repo.mysql.com/mysql57-community-release-el7.rpm
    state: present 
- name: Import a key from repo.mysql.com
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
- name: Install MySQL 5.7
  become: yes
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - mysql-community-client
      - MySQL-python
    state: installed
- name: Ensure mysql service is running
  become: yes
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes
- name: Find MySQL root password
  become: yes
  ansible.builtin.shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
  register: mysql_tmp_root_pass

#Detect and properly set root password 
- name: Detect and properly set root password - master
  block:
  - name: Detect .my.cnf file
    ansible.builtin.stat:
      path: /root/.my.cnf
    register: result
  - name: File .my.cnf exists
    community.mysql.mysql_user:
      name: root
      password: "{{ mysql_root_pass }}"
    when: result.stat.exists == true
  - name: Set new password from temporary password
    ansible.builtin.shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_pass }}'');" --connect-expired-password -uroot -p"{{ mysql_tmp_root_pass.stdout }}"'
    when: result.stat.exists == false
  become: true

- name: Create .my.cnf
  become: yes
  ansible.builtin.template:
   src: "templates/.my.cnf.j2"
   dest: "/root/.my.cnf"
   owner: root
   group: root
   mode: 0600
